{"tags": ["json", "ipython", "ipython-notebook"], "answers": [{"answer_id": 35460153, "question_id": 32103772, "body": "<p>I just had the same issue after upgrading from IPython 0.13 (ish) to Jupyter 4.</p>\n\n<p>The problem in my case were a few rogue trailing commas in the JSON, for example the comma following \"outputs\" in:</p>\n\n<pre><code>...\n \"language\": \"python\",\n \"metadata\": {},\n \"outputs\": [],\n},\n</code></pre>\n\n<p>After removing the commas, Jupyter/IPython could again read the notebook (and upgraded it to version 4). I hope this helps.</p>\n"}, {"answer_id": 44365270, "question_id": 32103772, "body": "<p>This happened to me as well. I opened my data.ipynb file using notepad and found out it was blank. </p>\n\n<p>I managed to recover my file by going into the hidden ipynb_checkpoints folder and copying data_checkpoint.ipynb out into my working directory.</p>\n\n<p>In my Mac OS terminal</p>\n\n<pre><code>cd .ipynb_checkpoints\ncp data-checkpoint.ipynb \\..\n</code></pre>\n\n<p>Thankfully the codes were preserved. Hope this helps!</p>\n"}, {"answer_id": 48705636, "question_id": 32103772, "body": "<p>In my case, I am using GitHub to save and share my ipython files with my teammate. When there is a conflict in the code, I had to delete those lines indicating the changes in the conflicting code such as:</p>\n\n<pre><code>&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;head\n=============\n</code></pre>\n\n<p>and It works for me.</p>\n"}, {"answer_id": 50722542, "question_id": 32103772, "body": "<p>I had this issue from accidentally saving as .txt from github and solved by deleting .txt (leaving .ipynb instead of .ipynb.txt when downloading)</p>\n"}, {"answer_id": 53641044, "question_id": 32103772, "body": "<p>Save yourself a headache. Open your .ipynb in any online JSON validator and it will tell you which lines have issues. I used <a href=\"https://www.freeformatter.com/json-validator.html\" rel=\"noreferrer\">this one</a>.</p>\n"}, {"answer_id": 55072665, "question_id": 32103772, "body": "<p>The easiest way to recover corrupted Jupyter notebook files, whether it contains text or not (size = 0KB), is to go to the project folder and display the hidden files. Once the hidden files are displayed, you will see a folder named '.ipynb_checkpoints'. Simply open this folder and take the file you want!</p>\n"}, {"answer_id": 59740205, "question_id": 32103772, "body": "<p>Yes, the best solution for me was I saved my notebook in HTML format, then opened it in Notepad ++ , delete the long repeated lines of output which were causing my notebook to grow to 45MB, once that cleared, Saved the file back into (.ipynb) format , and was able to opened it with no JSON error.\nHope that worked for others as well!</p>\n"}, {"answer_id": 65443432, "question_id": 32103772, "body": "<p>this can be changed to reformat your ipynb file to readable in jupyter notebook. check your other ipynb files(open in notepad) which are working fine with your jupyter notebook, check and compare at the end of the files in notepad. there you can reformat the file which is not working.</p>\n"}, {"answer_id": 65832564, "question_id": 32103772, "body": "<h1>Visual studio code procedure</h1>\n<p>This is my procedure that usually avoids me groping in the dark.</p>\n<ol>\n<li>I installed a json parser validator like this <a href=\"https://marketplace.visualstudio.com/items?itemName=AdrianSanguineti.json-parse-validator\" rel=\"nofollow noreferrer\">one</a>.</li>\n<li>Open the file and save a copy as .json file.</li>\n<li>Open the json and look for the errors.</li>\n<li>Save it back to the .ipynb extension.</li>\n</ol>\n<p>Usually, I manage to fix the errors quickly.</p>\n"}, {"answer_id": 68240105, "question_id": 32103772, "body": "<p>Jupyter autosaves in a specific way. It means You have accidentally closed the notebook before properly saving it.</p>\n<p>You need to look for three things -</p>\n<ul>\n<li>Search for <code>&lt;&lt;&lt;&lt;&lt;&lt;&lt;</code> and delete those lines.</li>\n<li>Search for <code>======</code> and replace those lines with <code>,</code>.</li>\n<li>Search for <code>&gt;&gt;&gt;&gt;&gt;&gt;&gt;</code> and delete those lines.</li>\n</ul>\n<p>It will work fine after this.</p>\n"}], "is_answered": true, "answer_count": 10, "last_activity_date": 1625347966, "question_id": 32103772, "title": "Unreadable Notebook NotJSONError(&#39;Notebook does not appear to be JSON: u\\&#39;{\\\\n &quot;cells&quot;: [\\\\n {\\\\n &quot;cell_type&quot;: &quot;...&#39;,)", "body": "<p>Getting this very strange error when I am trying to load my ipython notebook. Never had it before, and I cannot to my recollection, remember having done anything silly with ipython:</p>\n\n<pre class=\"lang-none prettyprint-override\"><code>Unreadable Notebook: /path/to/notebooks/results.ipynb NotJSONError('Notebook does not appear to be JSON: u\\'{\\\\n \"cells\": [\\\\n  {\\\\n   \"cell_type\": \"...',)\n</code></pre>\n\n<p>which is followed by</p>\n\n<pre class=\"lang-none prettyprint-override\"><code>400 GET /api/contents/results.ipynb?type=notebook&amp;_=1440010858974 (127.0.0.1) 36.17ms referer=http://localhost:8888/notebooks/results.ipynb\n</code></pre>\n"}